import asyncio
import json
import random
import re
import shutil
import subprocess
import sys
import threading
import time
import uuid
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from pathlib import Path
from queue import Empty, Queue
from typing import Any, Optional

import instaloader
import requests
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import FileResponse, StreamingResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

import os as _os  # alias so later "import os" if any doesn't collide

CODE_DIR = Path(_os.environ.get("FEEDSCRIPT_CODE_DIR", Path(__file__).parent)).resolve()
DATA_DIR = Path(_os.environ.get("FEEDSCRIPT_DATA_DIR", Path(__file__).parent)).resolve()
ROOT = DATA_DIR  # legacy alias used by run_transcribe_job for the default output base

SESSIONS_DIR = DATA_DIR / "sessions"
OUTPUT_DIR = DATA_DIR / "output"
STATIC_DIR = CODE_DIR / "static"
TEMPLATES_DIR = CODE_DIR / "templates"

for d in (SESSIONS_DIR, OUTPUT_DIR):
    d.mkdir(parents=True, exist_ok=True)

STATE_FILE = DATA_DIR / "state.json"
executor = ThreadPoolExecutor(max_workers=2)
_whisper_models: dict[str, Any] = {}
_jobs: dict[str, dict] = {}


def load_state() -> dict:
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {}


def save_state(state: dict) -> None:
    STATE_FILE.write_text(json.dumps(state, indent=2))


def human_sleep(min_s: float, max_s: float) -> None:
    time.sleep(random.uniform(min_s, max_s))


async def async_human_sleep(min_s: float, max_s: float) -> None:
    await asyncio.sleep(random.uniform(min_s, max_s))


def parse_cookies_blob(blob: str) -> dict:
    blob = blob.strip()
    if not blob:
        raise ValueError("Empty cookies")
    data = json.loads(blob)
    needed = {"sessionid", "ds_user_id", "csrftoken"}
    result: dict[str, str] = {}
    if isinstance(data, list):
        for entry in data:
            if isinstance(entry, dict):
                name = entry.get("name") or entry.get("Name")
                value = entry.get("value") or entry.get("Value")
                if name in needed and value:
                    result[name] = str(value)
    elif isinstance(data, dict):
        for k in needed:
            if k in data and data[k]:
                result[k] = str(data[k])
    missing = needed - result.keys()
    if missing:
        raise ValueError(f"Missing cookies: {', '.join(sorted(missing))}")
    return result


def export_cookies_netscape(session, path: Path) -> None:
    """Write the session cookies in the Netscape format yt-dlp expects.

    instaloader persists a session as a bare {name: value} dict, so cookies
    restored by load_session_from_file come back with no domain and no expiry.
    Taken literally that produced a cookie file with nothing usable in it —
    domain-less cookies were skipped outright, and an expiry of 0 reads as
    "expired in 1970" and is dropped when the file is loaded. Every download
    then ran logged out and Instagram answered "login required". Both fields
    get sensible defaults here instead.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    # A restored session cookie has no expiry attached but is still valid, so
    # give it a horizon comfortably past the end of any run.
    default_expiry = int(time.time()) + 365 * 24 * 3600
    lines = ["# Netscape HTTP Cookie File", "# Generated by Feedscript.", ""]
    written = 0
    for c in session.cookies:
        domain = c.domain or ".instagram.com"
        subdomain = "TRUE" if domain.startswith(".") else "FALSE"
        expires = int(c.expires) if c.expires else default_expiry
        secure = "TRUE" if c.secure else "FALSE"
        lines.append("\t".join([domain, subdomain, c.path or "/", secure, str(expires), c.name, c.value or ""]))
        written += 1
    if not any(c.name == "sessionid" and c.value for c in session.cookies):
        # Writing the file anyway would just produce downloads that fail as
        # "login required" several minutes later.
        raise RuntimeError("The saved session has no Instagram sessionid — log out and log in again.")
    path.write_text("\n".join(lines) + "\n")
    # The file holds a live session cookie; keep it out of other users' reach.
    try:
        path.chmod(0o600)
    except OSError:
        pass


def ytdlp_download(post_url: str, dest: Path, cookies_file: Path) -> Path:
    import yt_dlp
    dest.parent.mkdir(parents=True, exist_ok=True)
    base = dest.with_suffix("")
    opts = {
        "outtmpl": str(base) + ".%(ext)s",
        "format": "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/bestvideo+bestaudio/best",
        "merge_output_format": "mp4",
        "postprocessors": [{"key": "FFmpegVideoConvertor", "preferedformat": "mp4"}],
        "quiet": True,
        "no_warnings": True,
        "cookiefile": str(cookies_file),
        "noprogress": True,
        "overwrites": True,
        "retries": 3,
        "fragment_retries": 3,
    }
    with yt_dlp.YoutubeDL(opts) as ydl:
        ydl.download([post_url])
    for p in sorted(base.parent.glob(base.name + ".*")):
        if p.suffix.lower() in (".mp4", ".mkv", ".webm", ".mov", ".m4v"):
            if p != dest:
                p.rename(dest)
            return dest
    raise FileNotFoundError(f"No video could be downloaded for {post_url}")


def has_audio(path: Path) -> bool:
    try:
        r = subprocess.run(
            ["ffprobe", "-v", "error", "-select_streams", "a",
             "-show_entries", "stream=codec_type",
             "-of", "default=nw=1:nk=1", str(path)],
            capture_output=True, text=True, timeout=20,
        )
        return "audio" in r.stdout.strip()
    except Exception:
        return True


def build_meta(p: "TranscribePost", transcript: str, language: Optional[str], model: str, note: Optional[str] = None) -> dict:
    meta = {
        "shortcode": p.shortcode,
        "url": f"https://www.instagram.com/p/{p.shortcode}/",
        "caption": p.caption,
        "likes": p.likes,
        "comments": p.comments,
        "views": p.views,
        "timestamp": p.timestamp,
        "transcript": transcript,
        "transcript_language": language,
        "transcribed_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "whisper_model": model,
    }
    if note:
        meta["note"] = note
    return meta


def parse_date(s: Optional[str]) -> Optional[datetime]:
    if not s:
        return None
    s = s.strip()
    if not s:
        return None
    try:
        return datetime.fromisoformat(s).replace(tzinfo=timezone.utc)
    except ValueError:
        return datetime.strptime(s, "%Y-%m-%d").replace(tzinfo=timezone.utc)


def make_loader() -> instaloader.Instaloader:
    kwargs = dict(
        download_pictures=False,
        download_videos=False,
        download_video_thumbnails=False,
        download_geotags=False,
        download_comments=False,
        save_metadata=False,
        compress_json=False,
        quiet=True,
        # Two attempts: enough to ride out a single transient blip during a
        # long scan, but errors still surface in the UI quickly (the default
        # 3 attempts with long backoffs reads as the app hanging).
        max_connection_attempts=2,
    )
    # Enable the iPhone API path so Post.get_iphone_struct() works.
    # This is what gives us the accurate `play_count` that matches the
    # "views" number shown in the Instagram app.
    try:
        return instaloader.Instaloader(**kwargs, iphone_support=True)
    except TypeError:
        # Older instaloader versions don't accept iphone_support
        return instaloader.Instaloader(**kwargs)


def loader_with_session() -> instaloader.Instaloader:
    state = load_state()
    username = state.get("username")
    if not username:
        raise HTTPException(401, "Not logged in")
    session_file = SESSIONS_DIR / f"{username}.session"
    if not session_file.exists():
        raise HTTPException(401, "Session missing, re-login")
    L = make_loader()
    L.load_session_from_file(username, str(session_file))
    return L


# --------------------------------------------------------------------------
# Instagram web ("private") API
#
# instaloader reads through https://www.instagram.com/graphql/query, which
# started answering 401 "Please wait a few minutes before you try again." for
# logged-in sessions in mid-2026. That one endpoint carried profile listing,
# the like/comment/view fallbacks and test_login(), so its failure looks like
# the app losing its login — the symptom users see is "Profile not found" for
# accounts that plainly exist.
#
# The endpoints instagram.com's own frontend calls still answer normally with
# the very same cookies, so every read goes through them now. instaloader is
# kept for what it is still good at: password login, and reading/writing the
# saved session file.
# --------------------------------------------------------------------------

IG_APP_ID = "936619743392459"
IG_WEB_UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
             "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36")
IG_ORIGIN = "https://www.instagram.com"
IG_API_BASE = IG_ORIGIN + "/api/v1"
# The feed endpoint silently truncates a page to 12 items no matter what
# `count` asks for, so paging is the only way to go deeper.
IG_PAGE_SIZE = 12
# Ceiling on how far a single scan will page (12 posts each), so a target with
# thousands of posts and few videos cannot spin forever.
IG_MAX_PAGES = 200


class IGError(Exception):
    """Something went wrong talking to Instagram."""


class IGAuthError(IGError):
    """The session is not, or is no longer, signed in."""


class IGNotFound(IGError):
    """No such profile."""


class IGRateLimited(IGError):
    """Instagram asked us to slow down."""


def _cookie_value(session, name: str) -> str:
    for c in session.cookies:
        if c.name == name:
            return c.value or ""
    return ""


class InstagramWeb:
    """Thin client over Instagram's web API, sharing instaloader's cookie jar."""

    def __init__(self, loader: instaloader.Instaloader):
        self._loader = loader
        self._session = loader.context._session

    def _headers(self) -> dict:
        return {
            "User-Agent": IG_WEB_UA,
            "X-IG-App-ID": IG_APP_ID,
            "X-CSRFToken": _cookie_value(self._session, "csrftoken"),
            "X-Requested-With": "XMLHttpRequest",
            "Referer": IG_ORIGIN + "/",
            "Accept": "*/*",
        }

    def _get(self, url: str, params: Optional[dict] = None, timeout: int = 25):
        # Redirects are never followed: signed-out API calls bounce to the
        # login page, and some of them bounce in a loop that requests only
        # escapes by raising TooManyRedirects.
        try:
            return self._session.get(url, params=params, headers=self._headers(),
                                     timeout=timeout, allow_redirects=False)
        except requests.RequestException as e:
            raise IGError(f"Could not reach Instagram: {e}") from e

    def _get_json(self, url: str, params: Optional[dict] = None, timeout: int = 25) -> dict:
        r = self._get(url, params, timeout)
        if r.status_code in (301, 302, 303, 307, 308):
            if "/accounts/login" in r.headers.get("Location", ""):
                raise IGAuthError("Instagram has signed this session out. Log out in Feedscript and log in again.")
            raise IGError("Instagram redirected the request instead of answering it.")
        if r.status_code == 404:
            raise IGNotFound("Profile not found")
        if r.status_code == 429:
            raise IGRateLimited("Instagram is rate-limiting this account. Wait a few minutes and try again.")
        if r.status_code in (401, 403):
            raise IGAuthError(f"Instagram rejected the saved session (HTTP {r.status_code}). Log out and log in again.")
        if r.status_code >= 400:
            raise IGError(f"Instagram returned HTTP {r.status_code}.")
        try:
            data = r.json()
        except ValueError:
            if not (r.text or "").strip():
                raise IGError("Instagram returned an empty response — it is probably rate-limiting. Wait a few minutes.")
            raise IGError("Instagram returned a response this version cannot read.")
        if isinstance(data, dict) and data.get("status") == "fail":
            message = data.get("message") or "Instagram refused the request."
            if "few minutes" in message.lower() or "wait" in message.lower():
                raise IGRateLimited(message)
            raise IGError(message)
        return data if isinstance(data, dict) else {}

    def verify_session(self) -> Optional[bool]:
        """Whether the cookie jar is actually signed in — True, False, or None
        when Instagram would not say.

        /accounts/edit/ redirects to the login page when it is not and to the
        home page when it is — the cheapest yes/no Instagram still answers
        honestly now that test_login()'s graphql probe returns 401 either way.
        A 429 or a 5xx is not an answer, and must not be reported as a dead
        login.
        """
        try:
            r = self._get(IG_ORIGIN + "/accounts/edit/", timeout=20)
        except IGError:
            return None
        if r.status_code in (301, 302, 303, 307, 308):
            return "/accounts/login" not in r.headers.get("Location", "")
        if r.status_code == 200:
            return True
        return None

    def whoami(self) -> Optional[str]:
        """The username the cookies belong to, or None if it cannot be read."""
        uid = _cookie_value(self._session, "ds_user_id")
        if not uid:
            return None
        data = self._get_json(f"{IG_API_BASE}/feed/user/{uid}/", {"count": 1})
        return ((data.get("user") or {}).get("username")) or None

    def profile(self, username: str) -> dict:
        data = self._get_json(f"{IG_API_BASE}/users/web_profile_info/", {"username": username})
        user = (data.get("data") or {}).get("user")
        if not user:
            raise IGNotFound("Profile not found")
        return {
            "id": str(user.get("id") or ""),
            "username": user.get("username") or username,
            "full_name": user.get("full_name") or "",
            "followers": _api_int((user.get("edge_followed_by") or {}).get("count")),
            "posts_count": _api_int((user.get("edge_owner_to_timeline_media") or {}).get("count")),
            "is_private": bool(user.get("is_private")),
            "followed_by_viewer": bool(user.get("followed_by_viewer")),
        }

    def user_feed(self, user_id: str, max_id: Optional[str] = None) -> dict:
        params: dict = {"count": IG_PAGE_SIZE}
        if max_id:
            # Must be echoed back exactly: its suffix is the last item's owner
            # id, which is not always the profile being listed (collab posts).
            params["max_id"] = max_id
        return self._get_json(f"{IG_API_BASE}/feed/user/{user_id}/", params)


def _api_int(value):
    """Counts have to reach the UI as a number or null.

    A numeric *string* renders fine but sorts as NaN, and Instagram uses -1
    for counts the author has hidden, which would sort below every real value.
    """
    if value is None or isinstance(value, bool):
        return None
    if isinstance(value, str):
        value = value.strip()
        if not value.lstrip("-").isdigit():
            return None
        value = int(value)
    if isinstance(value, (int, float)):
        n = int(value)
        return n if n >= 0 else None
    return None


def _api_is_video(item: dict) -> bool:
    # media_type 1 = photo, 2 = video/reel, 8 = carousel. This API has no
    # is_video flag, and product_type is not a reliable stand-in.
    return item.get("media_type") == 2


def _api_thumbnail(item: dict) -> str:
    candidates = ((item.get("image_versions2") or {}).get("candidates")) or []
    for c in candidates:
        if isinstance(c, dict) and c.get("url"):
            return c["url"]
    return ""


def _api_video_url(item: dict) -> str:
    for v in (item.get("video_versions") or []):
        if isinstance(v, dict) and v.get("url"):
            return v["url"]
    return ""


def _api_taken_at(item: dict) -> Optional[datetime]:
    ts = item.get("taken_at")
    if not isinstance(ts, (int, float)) or isinstance(ts, bool):
        return None
    try:
        return datetime.fromtimestamp(ts, timezone.utc)
    except (OverflowError, OSError, ValueError):
        return None


def serialize_api_post(item: dict) -> dict:
    """Shape a feed item the way the table already expects it."""
    code = item.get("code") or ""
    taken_at = _api_taken_at(item)
    views = item.get("play_count")
    if views is None:
        views = item.get("ig_play_count")
    return {
        "shortcode": code,
        "url": f"{IG_ORIGIN}/p/{code}/",
        "caption": (((item.get("caption") or {}).get("text")) or "")[:2000],
        "likes": _api_int(item.get("like_count")),
        "comments": _api_int(item.get("comment_count")),
        "views": _api_int(views),
        "is_video": _api_is_video(item),
        "timestamp": taken_at.isoformat() if taken_at else None,
        "thumbnail": _api_thumbnail(item),
    }


# Shortcode -> (CDN video URL, when we learned it). Filled in while listing a
# profile so the transcribe step does not have to look every post up again.
# The URLs are signed and time-limited, hence the timestamp and the TTL.
_video_urls: dict = {}
# Shortcodes a completed walk did not find. Without this, every post that
# cannot be resolved costs another full walk of the feed.
_video_url_misses: set = set()
_video_urls_lock = threading.Lock()
_VIDEO_URL_TTL = 6 * 3600
_VIDEO_URL_MAX = 4000


def remember_video_url(shortcode: str, url: str) -> None:
    if not shortcode or not url:
        return
    with _video_urls_lock:
        _video_url_misses.discard(shortcode)
        if len(_video_urls) >= _VIDEO_URL_MAX:
            oldest = sorted(_video_urls, key=lambda k: _video_urls[k][1])
            for sc in oldest[: _VIDEO_URL_MAX // 4]:
                _video_urls.pop(sc, None)
        _video_urls[shortcode] = (url, time.time())


def lookup_video_url(shortcode: str) -> Optional[str]:
    with _video_urls_lock:
        entry = _video_urls.get(shortcode)
    if not entry:
        return None
    url, learned_at = entry
    if time.time() - learned_at > _VIDEO_URL_TTL:
        return None
    return url


def forget_video_url(shortcode: str) -> None:
    with _video_urls_lock:
        _video_urls.pop(shortcode, None)
        # Deliberately drops the miss too: forgetting is how a caller asks for
        # a fresh look, so it must not be short-circuited.
        _video_url_misses.discard(shortcode)


# Walking the feed to find one post costs the same as finding all of them, so
# a run resolves everything it still needs in a single pass. Doing it per post
# restarts at page 1 each time, which is quadratic over a long selection. The
# ceiling matches the listing scan, or a post the table legitimately showed
# could never be resolved again.
PREFETCH_MAX_PAGES = IG_MAX_PAGES


def prefetch_video_urls(api: InstagramWeb, target: str, shortcodes,
                        should_stop=None) -> None:
    """Cache video URLs for a whole run in one walk of the target's feed.

    Needed when the listing step did not leave them cached: a tab left open
    past the URLs' lifetime, or a server restarted between listing and
    transcribing.
    """
    with _video_urls_lock:
        known_missing = set(_video_url_misses)
    wanted = {sc for sc in shortcodes
              if sc and sc not in known_missing and not lookup_video_url(sc)}
    if not wanted:
        return
    try:
        user_id = api.profile(target)["id"]
    except IGError:
        return
    max_id = None
    for _ in range(PREFETCH_MAX_PAGES):
        if should_stop is not None and should_stop():
            return
        try:
            page = api.user_feed(user_id, max_id)
        except IGError:
            # Rate limited or signed out — that is not evidence the posts are
            # absent, so nothing is recorded as missing.
            return
        for item in page.get("items") or []:
            code = item.get("code") or ""
            remember_video_url(code, _api_video_url(item))
            wanted.discard(code)
        if not wanted:
            return
        max_id = page.get("next_max_id")
        if not page.get("more_available") or not max_id:
            break
        human_sleep(0.8, 1.6)
    # The walk finished without finding these, so stop walking for them.
    with _video_urls_lock:
        _video_url_misses.update(wanted)


def fetch_video(api: InstagramWeb, target: str, shortcode: str, dest: Path) -> Path:
    """Download one post's video, refreshing the signed URL if it has aged out."""
    url = lookup_video_url(shortcode)
    if not url:
        prefetch_video_urls(api, target, [shortcode])
        url = lookup_video_url(shortcode)
    if not url:
        raise IGError(f"No video URL could be found for {shortcode}")
    try:
        return download_video_direct(url, dest)
    except IGError:
        # Instagram's CDN links expire; the cached one may simply be too old.
        forget_video_url(shortcode)
        prefetch_video_urls(api, target, [shortcode])
        fresh = lookup_video_url(shortcode)
        if not fresh or fresh == url:
            raise
        return download_video_direct(fresh, dest)


def download_video_direct(url: str, dest: Path, timeout: int = 120) -> Path:
    """Stream a video straight from Instagram's CDN to disk.

    These URLs are pre-signed, so they need no cookies — and are deliberately
    sent none. What comes back is a progressive MP4 with the audio already
    muxed in, so unlike the yt-dlp path this needs no ffmpeg merge step.
    """
    dest.parent.mkdir(parents=True, exist_ok=True)
    part = dest.with_suffix(dest.suffix + ".part")
    expected = None
    try:
        with requests.get(url, stream=True, timeout=timeout,
                          headers={"User-Agent": IG_WEB_UA}) as r:
            r.raise_for_status()
            try:
                expected = int(r.headers.get("Content-Length") or 0) or None
            except ValueError:
                expected = None
            with open(part, "wb") as f:
                for chunk in r.iter_content(chunk_size=1 << 16):
                    if chunk:
                        f.write(chunk)
    except requests.RequestException as e:
        part.unlink(missing_ok=True)
        raise IGError(f"Video download failed: {e}") from e
    except OSError as e:
        part.unlink(missing_ok=True)
        raise IGError(f"Could not write the video to disk: {e}") from e
    size = part.stat().st_size
    if size == 0:
        part.unlink(missing_ok=True)
        raise IGError("Instagram returned an empty video file.")
    if expected is not None and size < expected:
        # A truncated file transcribes to nonsense rather than failing loudly.
        part.unlink(missing_ok=True)
        raise IGError(f"Video download was cut short ({size} of {expected} bytes).")
    part.replace(dest)
    return dest


app = FastAPI()
app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")


@app.get("/")
def index():
    return FileResponse(TEMPLATES_DIR / "index.html")


# Whether the saved session is still accepted by Instagram. Refreshed on a
# background thread and never on the request path: the launcher polls
# /api/auth/status with a one-second timeout to decide the server has come up,
# so this endpoint must not wait on Instagram.
_session_state: dict = {"ok": None, "checked_at": 0.0, "checking": False, "gen": 0}
_session_state_lock = threading.Lock()
_SESSION_CHECK_TTL = 300


def _refresh_session_state(generation: int) -> None:
    try:
        ok = InstagramWeb(loader_with_session()).verify_session()
    except Exception:
        # Offline, or Instagram was unreadable — report nothing rather than
        # claim the login has died.
        ok = None
    with _session_state_lock:
        if _session_state["gen"] != generation:
            # Someone logged in or out while this probe was in flight, so its
            # verdict is about an account we are no longer using.
            _session_state["checking"] = False
            return
        _session_state.update({"ok": ok, "checked_at": time.time(), "checking": False})


def _session_ok_cached():
    with _session_state_lock:
        stale = time.time() - _session_state["checked_at"] > _SESSION_CHECK_TTL
        if stale and not _session_state["checking"]:
            _session_state["checking"] = True
            generation = _session_state["gen"]
            threading.Thread(target=_refresh_session_state,
                             args=(generation,), daemon=True).start()
        return _session_state["ok"]


def _forget_session_state() -> None:
    with _session_state_lock:
        _session_state.update({"ok": None, "checked_at": 0.0, "checking": False,
                               "gen": _session_state["gen"] + 1})


@app.get("/api/auth/status")
def auth_status():
    state = load_state()
    username = state.get("username")
    if not username:
        return {"logged_in": False}
    if not (SESSIONS_DIR / f"{username}.session").exists():
        return {"logged_in": False}
    # session_ok is True / False / null (not checked yet or could not check).
    return {"logged_in": True, "username": username, "session_ok": _session_ok_cached()}


class PasswordLogin(BaseModel):
    username: str
    password: str


@app.post("/api/auth/password")
def auth_password(body: PasswordLogin):
    L = make_loader()
    try:
        L.login(body.username, body.password)
    except instaloader.exceptions.BadCredentialsException:
        raise HTTPException(400, "Bad credentials")
    except instaloader.exceptions.TwoFactorAuthRequiredException:
        raise HTTPException(400, "2FA required — use cookie login instead")
    except instaloader.exceptions.ConnectionException as e:
        raise HTTPException(400, f"Instagram blocked the login: {e}")
    except Exception as e:
        raise HTTPException(400, f"Login failed: {e}")
    session_file = SESSIONS_DIR / f"{body.username}.session"
    L.save_session_to_file(str(session_file))
    save_state({"username": body.username})
    _forget_session_state()
    return {"ok": True, "username": body.username}


class CookieLogin(BaseModel):
    sessionid: str
    ds_user_id: str
    csrftoken: str


@app.post("/api/auth/cookies")
def auth_cookies(body: CookieLogin):
    L = make_loader()
    s = L.context._session
    for name, value in {
        "sessionid": body.sessionid,
        "ds_user_id": body.ds_user_id,
        "csrftoken": body.csrftoken,
    }.items():
        s.cookies.set(name, value, domain=".instagram.com")
    api = InstagramWeb(L)
    signed_in = api.verify_session()
    if signed_in is False:
        raise HTTPException(400, "Instagram did not accept those cookies. Copy them again from a tab where you are signed in.")
    if signed_in is None:
        raise HTTPException(400, "Could not reach Instagram to check those cookies — it may be rate-limiting. Wait a minute and try again.")
    try:
        username = api.whoami()
    except IGError as e:
        raise HTTPException(400, f"Cookie check failed: {e}")
    if not username:
        raise HTTPException(400, "Could not read the account name from those cookies — check that ds_user_id was included.")
    L.context.username = username
    session_file = SESSIONS_DIR / f"{username}.session"
    L.save_session_to_file(str(session_file))
    save_state({"username": username})
    _forget_session_state()
    return {"ok": True, "username": username}


class CookieJsonLogin(BaseModel):
    blob: str


@app.post("/api/auth/cookies_json")
def auth_cookies_json(body: CookieJsonLogin):
    try:
        cookies = parse_cookies_blob(body.blob)
    except json.JSONDecodeError:
        raise HTTPException(400, "Not valid JSON — paste the cookies export directly")
    except ValueError as e:
        raise HTTPException(400, str(e))
    L = make_loader()
    s = L.context._session
    for name, value in cookies.items():
        s.cookies.set(name, value, domain=".instagram.com")
    api = InstagramWeb(L)
    signed_in = api.verify_session()
    if signed_in is False:
        raise HTTPException(400, "Instagram did not accept those cookies. Copy them again from a tab where you are signed in.")
    if signed_in is None:
        raise HTTPException(400, "Could not reach Instagram to check those cookies — it may be rate-limiting. Wait a minute and try again.")
    try:
        username = api.whoami()
    except IGError as e:
        raise HTTPException(400, f"Cookie check failed: {e}")
    if not username:
        raise HTTPException(400, "Could not read the account name from those cookies — check that ds_user_id was included.")
    L.context.username = username
    session_file = SESSIONS_DIR / f"{username}.session"
    L.save_session_to_file(str(session_file))
    save_state({"username": username})
    _forget_session_state()
    return {"ok": True, "username": username}


@app.post("/api/auth/logout")
def auth_logout():
    state = load_state()
    username = state.get("username")
    if username:
        f = SESSIONS_DIR / f"{username}.session"
        if f.exists():
            f.unlink()
    save_state({})
    _forget_session_state()
    return {"ok": True}


@app.get("/api/posts/{target}")
async def stream_posts(
    target: str,
    request: Request,
    limit: int = 200,
    date_from: Optional[str] = None,
    date_to: Optional[str] = None,
):
    target = target.strip().lstrip("@")
    events: Queue = Queue()
    stop = threading.Event()

    def produce():
        try:
            df = parse_date(date_from)
            dto = parse_date(date_to)
        except ValueError:
            events.put({"error": "Invalid date filter"})
            return
        try:
            L = loader_with_session()
        except HTTPException as e:
            events.put({"error": e.detail})
            return
        if stop.is_set():
            return

        api = InstagramWeb(L)
        try:
            prof = api.profile(target)
        except IGNotFound:
            events.put({"error": "Profile not found"})
            return
        except IGError as e:
            events.put({"error": str(e) or "Instagram request failed."})
            return
        except Exception as e:
            events.put({"error": str(e) or type(e).__name__ or "Instagram request failed."})
            return

        events.put({
            "type": "profile",
            "username": prof["username"],
            "full_name": prof["full_name"],
            "posts_count": prof["posts_count"],
            "followers": prof["followers"],
            "is_private": prof["is_private"],
        })

        if prof["is_private"] and not prof["followed_by_viewer"]:
            events.put({"error": "Profile is private and not followed"})
            return

        user_id = prof["id"]
        count = 0
        scanned = 0

        def end_early(message: str) -> None:
            """Close out a scan that stopped before it meant to.

            Anything already streamed is only usable once `done` arrives — that
            is what sorts the table and pre-checks the top rows — so a failure
            partway through reports the reason and still finishes, rather than
            leaving the user with rows they cannot act on.
            """
            if count:
                events.put({"type": "status", "message": message})
                events.put({"type": "done", "count": count, "scanned": scanned})
            else:
                events.put({"error": message})

        seen: set = set()
        max_id: Optional[str] = None
        pages = 0

        try:
            while True:
                if stop.is_set():
                    return
                page = api.user_feed(user_id, max_id)
                pages += 1
                items = page.get("items") or []
                if not items:
                    break

                finished = False
                for item in items:
                    if stop.is_set():
                        return
                    code = item.get("code")
                    if not code or code in seen:
                        # Pinned posts are served at the top of the feed and
                        # then again in date order.
                        continue
                    seen.add(code)
                    scanned += 1

                    taken_at = _api_taken_at(item)
                    pinned = any(str(u) == user_id
                                 for u in (item.get("timeline_pinned_user_ids") or []))
                    if df and taken_at and taken_at < df:
                        # A pinned post can be years old and still lead the
                        # feed, so it must not end a date-filtered scan.
                        if pinned:
                            continue
                        finished = True
                        break
                    if not _api_is_video(item):
                        continue
                    if dto and taken_at and taken_at > dto:
                        continue

                    remember_video_url(code, _api_video_url(item))
                    count += 1
                    events.put({"type": "post", "post": serialize_api_post(item)})
                    if count >= limit:
                        finished = True
                        break

                if finished:
                    break
                max_id = page.get("next_max_id")
                if not page.get("more_available") or not max_id:
                    break
                if pages >= IG_MAX_PAGES:
                    # Say so rather than letting a truncated scan read as
                    # "that is everything this account has".
                    events.put({"type": "status",
                                "message": f"Stopped after scanning {scanned} posts — narrow the date range to reach older ones."})
                    break
                if pages % 10 == 0:
                    events.put({"type": "status",
                                "message": f"Scanned {scanned} posts, {count} videos so far…"})
                human_sleep(0.8, 1.8)
        except IGRateLimited as e:
            end_early(str(e) or "Instagram is rate-limiting this account.")
            return
        except IGError as e:
            end_early(str(e) or "Instagram request failed.")
            return
        except Exception as e:
            end_early("Stopped: " + (str(e) or type(e).__name__))
            return

        events.put({"type": "done", "count": count, "scanned": scanned})

    def produce_safely():
        # All instaloader work happens on this worker thread: its blocking
        # requests must never run on the event loop, or every other request
        # (and the whole UI) freezes until Instagram answers.
        try:
            produce()
        except Exception as e:
            events.put({"error": str(e) or type(e).__name__})
        finally:
            events.put(None)

    async def gen():
        threading.Thread(target=produce_safely, daemon=True).start()
        try:
            while True:
                if await request.is_disconnected():
                    return
                try:
                    item = events.get_nowait()
                except Empty:
                    await asyncio.sleep(0.15)
                    continue
                if item is None:
                    return
                yield sse_event(item)
        finally:
            # Tell the worker to stop scanning — an abandoned stream must not
            # keep spending Instagram's rate budget.
            stop.set()

    return StreamingResponse(gen(), media_type="text/event-stream")


def sse_event(data: dict) -> str:
    return f"data: {json.dumps(data)}\n\n"


class TranscribePost(BaseModel):
    shortcode: str
    caption: str = ""
    likes: Optional[int] = None
    comments: Optional[int] = None
    views: Optional[int] = None
    timestamp: Optional[str] = None


class TranscribeRequest(BaseModel):
    target: str
    posts: list[TranscribePost]
    model: str = "small"
    run_name: Optional[str] = None
    output_dir: Optional[str] = None


def safe_name(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]", "_", s).strip("_") or "run"


_finals_lock = threading.Lock()
_active_finals: set = set()


def _reserve_final_file(out_dir: Path, run_name: str) -> Path:
    """Pick a results path no other *running* job owns.

    Two jobs submitted in the same second get the same timestamp run_name
    (and a re-used custom name collides too); without this, whichever job
    finishes last silently overwrites the other's transcripts. Re-running
    with the same name after a job has finished still replaces the old
    file, as before.
    """
    with _finals_lock:
        candidate = out_dir / f"{run_name}.json"
        n = 2
        while candidate in _active_finals:
            candidate = out_dir / f"{run_name}_{n}.json"
            n += 1
        _active_finals.add(candidate)
        return candidate


def _sweep_stale_tmp(out_dir: Path) -> None:
    """Remove _tmp_* dirs older than a day — leftovers from crashed or
    force-quit jobs that never reached their own cleanup."""
    cutoff = time.time() - 24 * 3600
    try:
        for d in out_dir.glob("_tmp_*"):
            if d.is_dir() and d.stat().st_mtime < cutoff:
                shutil.rmtree(d, ignore_errors=True)
    except OSError:
        pass


def get_whisper(model_name: str):
    import whisper
    if model_name not in _whisper_models:
        _whisper_models[model_name] = whisper.load_model(model_name)
    return _whisper_models[model_name]


def emit(job: dict, event: dict) -> None:
    event["at"] = time.time()
    job["events"].append(event)


def run_transcribe_job(job_id: str, req: TranscribeRequest):
    job = _jobs[job_id]
    final_file: Optional[Path] = None
    temp_dir: Optional[Path] = None
    cookies_dir: Optional[Path] = None
    try:
        L = loader_with_session()
        target = req.target.strip().lstrip("@")
        ts = time.strftime("%Y-%m-%d_%H-%M-%S")
        run_name = safe_name(req.run_name) if req.run_name else ts

        if req.output_dir:
            base_out = Path(req.output_dir).expanduser()
            if not base_out.is_absolute():
                base_out = (ROOT / base_out).resolve()
            else:
                base_out = base_out.resolve()
        else:
            base_out = OUTPUT_DIR
        base_out.mkdir(parents=True, exist_ok=True)
        out_dir = base_out / safe_name(target)
        out_dir.mkdir(parents=True, exist_ok=True)
        _sweep_stale_tmp(out_dir)
        final_file = _reserve_final_file(out_dir, run_name)
        run_name = final_file.stem
        # uuid suffix: two jobs started in the same second must not share a
        # temp dir, or their downloads overwrite each other.
        temp_dir = out_dir / f"_tmp_{run_name}_{uuid.uuid4().hex[:6]}"
        temp_dir.mkdir(exist_ok=True)
        job["out_dir"] = str(out_dir)
        job["final_file"] = str(final_file)

        api = InstagramWeb(L)

        def ensure_cookies() -> Path:
            """The cookie file yt-dlp needs, created on first use.

            It holds a live Instagram session, so it is written only if the
            fallback is actually reached, and into the app's own data
            directory rather than the chosen output folder — that is routinely
            a synced Dropbox or Desktop path. The direct CDN path is
            pre-signed and is deliberately sent no cookies at all.
            """
            nonlocal cookies_dir
            if cookies_dir is None:
                cookies_dir = DATA_DIR / f"_cookies_{job_id}"
                cookies_dir.mkdir(parents=True, exist_ok=True)
                try:
                    cookies_dir.chmod(0o700)
                except OSError:
                    pass
                export_cookies_netscape(L.context._session, cookies_dir / "cookies.txt")
            return cookies_dir / "cookies.txt"

        total = len(req.posts)
        emit(job, {"type": "job_start", "total": total, "target": target, "final_file": str(final_file)})
        emit(job, {"type": "phase_start", "phase": "download", "total": total})
        emit(job, {"type": "phase_start", "phase": "transcribe", "total": total})

        work_queue: Queue = Queue(maxsize=3)
        results: list[dict] = []
        results_lock = threading.Lock()

        def downloader():
            try:
                if not job.get("cancelled"):
                    # One walk of the feed resolves every URL this run still
                    # needs; doing it per post would restart at page 1 each
                    # time and grow quadratically with the selection.
                    prefetch_video_urls(api, target, [p.shortcode for p in req.posts],
                                        should_stop=lambda: bool(job.get("cancelled")))
                for idx, p in enumerate(req.posts):
                    if job.get("cancelled"):
                        break
                    sc = p.shortcode
                    # The shortcode arrives in the request body, so it must not
                    # be trusted to be a safe path component.
                    vp = temp_dir / f"{safe_name(sc)}.mp4"
                    url = f"https://www.instagram.com/p/{sc}/"
                    emit(job, {"type": "item_start", "phase": "download", "index": idx, "total": total, "shortcode": sc})
                    try:
                        try:
                            # Preferred path: Instagram's own CDN URL. It is a
                            # progressive MP4 with audio already muxed in, so
                            # it needs neither an extractor nor an ffmpeg merge.
                            fetch_video(api, target, sc, vp)
                        except (IGError, OSError) as e:
                            # yt-dlp remains the safety net for anything the
                            # API path could not resolve.
                            emit(job, {"type": "log", "message": f"Direct download of {sc} failed ({e}); trying yt-dlp."})
                            ytdlp_download(url, vp, ensure_cookies())
                        emit(job, {"type": "item_done", "phase": "download", "index": idx, "total": total, "shortcode": sc, "bytes": vp.stat().st_size})
                        work_queue.put((idx, p, vp))
                    except Exception as e:
                        emit(job, {"type": "item_error", "phase": "download", "shortcode": sc, "error": str(e) or type(e).__name__})
                    if idx < total - 1 and not job.get("cancelled"):
                        human_sleep(2.0, 5.0)
            finally:
                work_queue.put(None)

        def transcriber():
            whisper_mod = None
            while True:
                item = work_queue.get()
                if item is None:
                    break
                if job.get("cancelled"):
                    try:
                        item[2].unlink(missing_ok=True)
                    except Exception:
                        pass
                    continue
                idx, p, vp = item
                sc = p.shortcode
                emit(job, {"type": "item_start", "phase": "transcribe", "index": idx, "total": total, "shortcode": sc})
                try:
                    if not has_audio(vp):
                        meta = build_meta(p, "", None, req.model, note="no audio track")
                        emit(job, {"type": "item_skip", "phase": "transcribe", "shortcode": sc, "reason": "no audio track"})
                    else:
                        if whisper_mod is None:
                            emit(job, {"type": "log", "message": "Loading transcription model…"})
                            whisper_mod = get_whisper(req.model)
                            emit(job, {"type": "log", "message": "Transcription model ready"})
                        result = whisper_mod.transcribe(str(vp), fp16=False)
                        meta = build_meta(p, result["text"].strip(), result.get("language"), req.model)
                        emit(job, {"type": "item_done", "phase": "transcribe", "index": idx, "total": total, "shortcode": sc})
                    with results_lock:
                        results.append(meta)
                except Exception as e:
                    emit(job, {"type": "item_error", "phase": "transcribe", "shortcode": sc, "error": str(e) or type(e).__name__})
                finally:
                    vp.unlink(missing_ok=True)

        dl_thread = threading.Thread(target=downloader, daemon=True)
        tx_thread = threading.Thread(target=transcriber, daemon=True)
        dl_thread.start()
        tx_thread.start()
        dl_thread.join()
        tx_thread.join()

        summary = {
            "target": target,
            "run_name": run_name,
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
            "whisper_model": req.model,
            "count": len(results),
            "videos": sorted(results, key=lambda r: r.get("shortcode", "")),
        }
        final_file.write_text(json.dumps(summary, indent=2, ensure_ascii=False))

        if job.get("cancelled"):
            emit(job, {"type": "job_cancelled", "final_file": str(final_file)})
        else:
            emit(job, {"type": "job_done", "final_file": str(final_file)})
        job["done"] = True
    except Exception as e:
        emit(job, {"type": "job_error", "error": str(e) or type(e).__name__})
        job["done"] = True
    finally:
        # Always, even on a crash: the temp dir can hold a cookies.txt with a
        # live Instagram session in the user's own output folder.
        if temp_dir is not None:
            _cleanup_temp(temp_dir)
        if cookies_dir is not None:
            shutil.rmtree(cookies_dir, ignore_errors=True)
        if final_file is not None:
            with _finals_lock:
                _active_finals.discard(final_file)


def _cleanup_temp(temp_dir: Path) -> None:
    try:
        for leftover in temp_dir.iterdir():
            leftover.unlink(missing_ok=True)
        temp_dir.rmdir()
    except OSError:
        pass


@app.post("/api/transcribe")
def transcribe_start(req: TranscribeRequest):
    if not req.posts:
        raise HTTPException(400, "No posts selected")
    # Duplicate shortcodes (e.g. a pinned reel selected twice) would download
    # to the same paths concurrently and corrupt each other.
    seen: set = set()
    unique_posts = []
    for p in req.posts:
        if p.shortcode not in seen:
            seen.add(p.shortcode)
            unique_posts.append(p)
    req.posts = unique_posts
    job_id = uuid.uuid4().hex
    _jobs[job_id] = {"events": [], "done": False, "cancelled": False}
    executor.submit(run_transcribe_job, job_id, req)
    return {"job_id": job_id}


@app.get("/api/transcribe/{job_id}/events")
async def transcribe_events(job_id: str, request: Request):
    if job_id not in _jobs:
        raise HTTPException(404, "Unknown job")

    async def gen():
        sent = 0
        while True:
            if await request.is_disconnected():
                return
            job = _jobs[job_id]
            while sent < len(job["events"]):
                yield sse_event(job["events"][sent])
                sent += 1
            if job.get("done") and sent >= len(job["events"]):
                return
            await asyncio.sleep(0.3)

    return StreamingResponse(gen(), media_type="text/event-stream")


@app.post("/api/transcribe/{job_id}/cancel")
def transcribe_cancel(job_id: str):
    if job_id not in _jobs:
        raise HTTPException(404, "Unknown job")
    _jobs[job_id]["cancelled"] = True
    return {"ok": True}


@app.post("/api/clipboard")
def set_clipboard(body: dict):
    content = body.get("content", "")
    if not isinstance(content, str):
        raise HTTPException(400, "content must be a string")
    try:
        if sys.platform == "win32":
            subprocess.run(["clip"], input=content, text=True, check=True, timeout=10, shell=False)
        elif sys.platform == "darwin":
            subprocess.run(["pbcopy"], input=content, text=True, check=True, timeout=10)
        else:
            for cmd in (["xclip", "-selection", "clipboard"], ["xsel", "-b", "-i"]):
                try:
                    subprocess.run(cmd, input=content, text=True, check=True, timeout=10)
                    break
                except FileNotFoundError:
                    continue
            else:
                raise HTTPException(500, "No clipboard tool available (install xclip or xsel)")
    except FileNotFoundError:
        raise HTTPException(500, "Clipboard tool not available on this system")
    except subprocess.CalledProcessError as e:
        raise HTTPException(500, f"Copy failed: {e}")
    return {"ok": True}


@app.post("/api/reveal")
def reveal_folder(body: dict):
    path = body.get("path")
    if not path or not Path(path).exists():
        raise HTTPException(400, "Path not found")
    p = Path(path)
    if sys.platform == "win32":
        if p.is_file():
            subprocess.run(["explorer", "/select,", str(p)], check=False)
        else:
            subprocess.run(["explorer", str(p)], check=False)
    elif sys.platform == "darwin":
        if p.is_file():
            subprocess.run(["open", "-R", str(p)], check=False)
        else:
            subprocess.run(["open", str(p)], check=False)
    else:
        target = str(p) if p.is_dir() else str(p.parent)
        subprocess.run(["xdg-open", target], check=False)
    return {"ok": True}


def _scan_runs(base: Path) -> list[dict]:
    runs: list[dict] = []
    if not base.exists():
        return runs
    for target_dir in base.iterdir():
        if not target_dir.is_dir() or target_dir.name.startswith("_") or target_dir.name.startswith("."):
            continue
        for entry in target_dir.iterdir():
            if entry.name.startswith(".") or entry.name.startswith("_"):
                continue
            if entry.is_file() and entry.suffix == ".json":
                data = _safe_read_summary(entry)
                if data is None:
                    continue
                runs.append({
                    "kind": "file",
                    "path": str(entry),
                    "base": str(base),
                    "target": target_dir.name,
                    "run_name": entry.stem,
                    "generated_at": data.get("generated_at"),
                    "count": data.get("count", len(data.get("videos", []))),
                    "size": entry.stat().st_size,
                    "whisper_model": data.get("whisper_model"),
                })
            elif entry.is_dir():
                summary = entry / "_summary.json"
                if not summary.exists():
                    continue
                data = _safe_read_summary(summary)
                if data is None:
                    continue
                size = 0
                for x in entry.rglob("*"):
                    if x.is_file():
                        try:
                            size += x.stat().st_size
                        except OSError:
                            pass
                runs.append({
                    "kind": "folder",
                    "path": str(entry),
                    "base": str(base),
                    "target": target_dir.name,
                    "run_name": entry.name,
                    "generated_at": data.get("generated_at"),
                    "count": data.get("count", len(data.get("videos", []))),
                    "size": size,
                    "whisper_model": data.get("whisper_model"),
                })
    return runs


def _safe_read_summary(path: Path) -> Optional[dict]:
    try:
        data = json.loads(path.read_text())
    except Exception:
        return None
    if not isinstance(data, dict) or "videos" not in data:
        return None
    return data


@app.get("/api/library")
def library_list(output_dir: Optional[str] = None):
    bases: list[Path] = [OUTPUT_DIR]
    if output_dir:
        custom = Path(output_dir).expanduser()
        if not custom.is_absolute():
            custom = (ROOT / custom).resolve()
        else:
            custom = custom.resolve()
        if custom.exists() and custom not in bases:
            bases.append(custom)
    runs: list[dict] = []
    for base in bases:
        runs.extend(_scan_runs(base))
    runs.sort(key=lambda r: r.get("generated_at") or "", reverse=True)
    return {"runs": runs}


@app.get("/api/library/file")
def library_read(path: str):
    p = Path(path).resolve()
    if not p.exists() or not p.is_file():
        raise HTTPException(404, "Not found")
    if p.suffix != ".json":
        raise HTTPException(400, "Not a JSON file")
    try:
        content = p.read_text()
    except Exception as e:
        raise HTTPException(500, str(e))
    return {"filename": p.name, "content": content, "size": p.stat().st_size}


class DeleteLibraryItem(BaseModel):
    path: str
    kind: str


@app.post("/api/library/delete")
def library_delete(body: DeleteLibraryItem):
    p = Path(body.path).resolve()
    if not p.exists():
        raise HTTPException(404, "Not found")
    try:
        if body.kind == "folder":
            if not p.is_dir():
                raise HTTPException(400, "Path is not a folder")
            shutil.rmtree(p)
        elif body.kind == "file":
            if not p.is_file():
                raise HTTPException(400, "Path is not a file")
            p.unlink()
            parent = p.parent
            if parent != OUTPUT_DIR and parent.exists() and not any(parent.iterdir()):
                try:
                    parent.rmdir()
                except OSError:
                    pass
        else:
            raise HTTPException(400, "Unknown kind")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(500, str(e))
    return {"ok": True}
